import os

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://geo:geo_secret_2024@db:5432/geomodeler")
CORS_ORIGINS = os.getenv("CORS_ORIGINS", "http://localhost:8080").split(",")
MAX_BOREHOLES = 500
MAX_LAYERS_PER_BOREHOLE = 30
MAX_GRID_NX = 100
MAX_GRID_NY = 100
MAX_GRID_NZ = 50
CHINA_LON_MIN = 73.0
CHINA_LON_MAX = 135.0
CHINA_LAT_MIN = 3.0
CHINA_LAT_MAX = 54.0
CONVEX_HULL_EXPAND_RATIO = 0.10
UNIFORMITY_RATIO_THRESHOLD = 3.0
